//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class curso_professor
    {
        public int id { get; set; }
        public int id_curso { get; set; }
        public int id_professor { get; set; }
    
        public virtual curso curso { get; set; }
        public virtual professor professor { get; set; }
    }
}
