//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class projEscolaEntities : DbContext
    {
        public projEscolaEntities()
            : base("name=projEscolaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aluno> aluno { get; set; }
        public virtual DbSet<curso> curso { get; set; }
        public virtual DbSet<curso_professor> curso_professor { get; set; }
        public virtual DbSet<professor> professor { get; set; }
    }
}
